### ISSUE TITLE
Issue Hipotetico

### ISSUE THREAD

**Issue by lodurr** [maestria-geotel-201902/unidad-0-asignacion-1-asig-conrstudio-issues-lodurr#1]
Desarrollo Issue para asignación 1. El inconveniente que tuve es que firefox developer no deja copiar y pegar con Ctrl C - Ctrl V por lo que se debe realizar la digitación completa

**Comment by geofis** [comment]
Oh, vaya, pero supongo que habrá algún *workaround*.
